apiVersion: v1
kind: Secret
metadata:
  name: sec-as-env-manifest
  annotations:
    avp.kubernetes.io/path: "secret/data/demo"
type: Opaque
stringData:
  password: <pass>
  user: <user>
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-as-env-manifest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sec-as-env-manifest
  template:
    metadata:
      labels:
        app: sec-as-env-manifest
    spec:
      containers:
      - name: sec-as-env-manifest
        image: busybox
        # env:
        # - name: USER
        #   value: <path:kv-v2/data/argocd#user>
        # - name: PASSWORD
        #   value: <path:kv-v2/data/argocd#password>
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-as-env-manifest
              key: password
        - name: USER
          valueFrom:
            secretKeyRef:
              name: sec-as-env-manifest
              key: user

        command: ["sh","-c","echo user=$(USER) password=$(PASSWORD);sleep 365d"]
